# -*- coding: utf-8 -*-
"""IngenieriaDatosOuter_BusinessPayments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Layola27/Proyecto2-IA/blob/Gerard/IngenieriaDatosOuter_BusinessPayments.ipynb
"""

# Importando la biblioteca pandas para manipulación y análisis de datos
import pandas as pd

# Importando NumPy para operaciones numéricas y manipulación de arreglos
import numpy as np

# Importando Seaborn para visualización de datos estadísticos (opcional, pero puede complementar a Plotly)
import seaborn as sns

# Importando Plotly Express para visualizaciones interactivas de alto nivel y fáciles de usar
import plotly.express as px

# Importando matplotlib.pyplot para crear gráficos y visualizaciones
import matplotlib.pyplot as plt

# Importando Plotly Graph Objects para un control más detallado sobre las visualizaciones
import plotly.graph_objects as go

# Importando itertools para generar combinaciones de columnas
import itertools

# Importando la función seasonal_decompose para la descomposición de series temporales
from statsmodels.tsa.seasonal import seasonal_decompose

usuarios_activos = pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/usuarios_activos_actualizado.csv')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Configurar el tamaño del gráfico
plt.figure(figsize=(12, 8))

# Crear un mapa de calor de los valores faltantes
sns.heatmap(usuarios_activos.isnull(), cbar=False, cmap="viridis", yticklabels=False)

# Agregar título
plt.title("Mapa de calor de valores faltantes", fontsize=16)
plt.xlabel("Columnas", fontsize=12)
plt.ylabel("Filas", fontsize=12)

# Mostrar el gráfico
plt.show()

usuarios_activos.describe()

usuarios_activos.info()

# Obteniendo una lista de las columnas del DataFrame
columnas_usuarios_activos = usuarios_activos.columns.tolist()

for i in columnas_usuarios_activos:
    print("===========================")
    print(f"Columna: {i}")
    print(usuarios_activos[i].value_counts().head(10))
    print()

import pandas as pd
import plotly.express as px

# --- Preparación del DataFrame ---
# Se asume que ya tienes cargado el DataFrame 'usuarios_activos'
# y que 'columnas_usuarios_activos' es una lista con los nombres de las columnas de interés.
# Ejemplo:
# usuarios_activos = pd.read_csv('ruta/al/archivo.csv')
# columnas_usuarios_activos = ['columna1', 'columna2', 'columna3', ...]

# Opcional: Visualiza las primeras filas para confirmar la carga correcta
print(usuarios_activos.head())

# --- Filtrar columnas numéricas ---
# Si columnas_usuarios_activos contiene columnas no numéricas, filtramos solo las numéricas:
columnas_numericas = [
    col for col in columnas_usuarios_activos
    if pd.api.types.is_numeric_dtype(usuarios_activos[col])
]

# Si prefieres obtener directamente todas las columnas numéricas del DataFrame (sin depender de la lista anterior), podrías usar:
# columnas_numericas = usuarios_activos.select_dtypes(include='number').columns.tolist()

print(f"Columnas numéricas a analizar: {columnas_numericas}")

# --- Generar y mostrar histogramas ---
for columna in columnas_numericas:
    fig = px.histogram(
        usuarios_activos,
        x=columna,
        title=f'Histograma de {columna}',
        template='plotly_white'  # Estilo limpio de Plotly
    )
    # Ajustar la altura del gráfico
    fig.update_layout(height=500)
    # Mostrar el gráfico en Colab
    fig.show()

import pandas as pd
import plotly.express as px

# --- Cargar el DataFrame ---
# Se asume que ya tienes cargado tu DataFrame 'usuarios_activos'
# Ejemplo:
# usuarios_activos = pd.read_csv('ruta/al/archivo.csv')

# --- Definir la lista de columnas a analizar ---
# Asegúrate de que 'columnas_usuarios_activos' contenga los nombres de las columnas que deseas considerar.
# Si no lo has definido, puedes obtener todas las columnas del dataset:
# columnas_usuarios_activos = usuarios_activos.columns.tolist()

# --- Identificar las columnas de interés ---
columnas_dataset = columnas_usuarios_activos

# --- Filtrar columnas numéricas ---
# Utilizamos describe() para extraer las columnas numéricas (describe solo calcula estadísticas para datos numéricos)
columnas_numericas = usuarios_activos[columnas_dataset].describe().columns.tolist()

print("Columnas numéricas detectadas:", columnas_numericas)

# --- Iterar sobre cada columna para identificar y graficar las categóricas con ≤ 10 valores únicos ---
for columna in columnas_dataset:
    # Procesamos únicamente las columnas que no son numéricas
    if columna not in columnas_numericas:
        # Contar la frecuencia de cada valor en la columna
        counts = usuarios_activos[columna].value_counts()

        # Si la cantidad de valores únicos es 10 o menos, graficamos
        if len(counts) <= 10:
            fig = px.pie(
                names=counts.index,
                values=counts.values,
                title=f'Distribución de {columna}',
                template='plotly_white'  # Estilo visual limpio
            )
            # Ajustar la altura del gráfico
            fig.update_layout(height=300)
            # Mostrar el gráfico de pastel
            fig.show()

import pandas as pd
import plotly.express as px

# --- Asegúrate de tener cargado el DataFrame 'usuarios_activos' ---
# Por ejemplo:
# usuarios_activos = pd.read_csv('ruta/al/archivo.csv')

# --- Define la lista de columnas a analizar ---
# Si ya cuentas con una lista de columnas, úsala; de lo contrario, puedes utilizar todas las columnas:
# columnas_usuarios_activos = usuarios_activos.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_activos
    if pd.api.types.is_numeric_dtype(usuarios_activos[col])
]

print("Columnas numéricas a graficar:", columnas_numericas)

# --- Crear diagramas de caja para cada columna numérica ---
for columna in columnas_numericas:
    fig = px.box(
        usuarios_activos,
        y=columna,
        title=f'Boxplot de {columna}',
        template='plotly_white'  # Estilo visual limpio
    )
    # Ajustar la altura del gráfico para una mejor visualización
    fig.update_layout(height=500)
    # Mostrar el gráfico
    fig.show()

import pandas as pd
import plotly.express as px

# --- Asegúrate de tener cargado el DataFrame 'usuarios_activos' ---
# Por ejemplo:
# usuarios_activos = pd.read_csv('ruta/al/archivo.csv')

# --- Define la lista de columnas a analizar ---
# Si ya cuentas con una lista de columnas, úsala; de lo contrario, puedes obtener todas las columnas:
# columnas_usuarios_activos = usuarios_activos.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_activos
    if pd.api.types.is_numeric_dtype(usuarios_activos[col])
]

print("Columnas numéricas a graficar:", columnas_numericas)

# --- Crear diagramas de violín para cada columna numérica ---
for columna in columnas_numericas:
    fig = px.violin(
        usuarios_activos,
        y=columna,
        title=f'Violinplot de {columna}',
        template='plotly_white'  # Estilo visual limpio
    )
    # Ajustar la altura del gráfico para una visualización óptima
    fig.update_layout(height=500)
    # Mostrar el gráfico
    fig.show()

import itertools
import matplotlib.pyplot as plt
import pandas as pd

# --- Asegúrate de tener cargado el DataFrame 'usuarios_activos' ---
# Por ejemplo:
# usuarios_activos = pd.read_csv('ruta/al/archivo.csv')

# --- Define la lista de columnas a analizar ---
# Si ya cuentas con una lista de columnas específicas, utilízala; de lo contrario, puedes usar todas las columnas:
# columnas_usuarios_activos = usuarios_activos.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_activos
    if pd.api.types.is_numeric_dtype(usuarios_activos[col])
]

print("Columnas numéricas a graficar:", columnas_numericas)

# --- Generar gráficos de dispersión para todas las combinaciones de columnas numéricas ---
for c1, c2 in itertools.combinations(columnas_numericas, 2):
    plt.figure(figsize=(8, 6))
    plt.scatter(usuarios_activos[c1], usuarios_activos[c2], alpha=0.7, edgecolor='k')
    plt.title(f'Gráfico de dispersión de {c1} vs {c2}', fontsize=14)
    plt.xlabel(c1, fontsize=12)
    plt.ylabel(c2, fontsize=12)
    plt.grid(True)
    plt.tight_layout()
    plt.show()

import itertools
import plotly.express as px
import pandas as pd

# --- Asegúrate de tener cargado el DataFrame 'usuarios_activos' ---
# Por ejemplo:
# usuarios_activos = pd.read_csv('ruta/al/archivo.csv')

# --- Define la lista de columnas a analizar ---
# Si ya cuentas con una lista de columnas específicas, úsala; de lo contrario, puedes utilizar todas las columnas:
# columnas_usuarios_activos = usuarios_activos.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_activos
    if pd.api.types.is_numeric_dtype(usuarios_activos[col])
]

print("Columnas numéricas a analizar:", columnas_numericas)

# --- Generar gráficos de dispersión con línea de tendencia para cada combinación de columnas numéricas ---
for c1, c2 in itertools.combinations(columnas_numericas, 2):
    fig = px.scatter(
        usuarios_activos,
        x=c1,
        y=c2,
        title=f'Gráfico de dispersión de {c1} vs {c2} con línea de tendencia',
        trendline="ols",  # Agrega la línea de tendencia usando Ordinary Least Squares
        template='plotly_white'  # Estilo limpio y minimalista
    )
    # Ajustar los rangos y la altura del gráfico
    fig.update_layout(
        height=500,
        xaxis=dict(title=c1, automargin=True),
        yaxis=dict(title=c2, automargin=True)
    )
    # Mostrar el gráfico de dispersión con línea de tendencia
    fig.show()

import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
import pandas as pd

# --- Asegúrate de tener cargado el DataFrame 'usuarios_activos' ---
# Por ejemplo:
# usuarios_activos = pd.read_csv('ruta/al/archivo.csv', parse_dates=['fecha'], index_col='fecha')

# --- Define la lista de columnas a analizar ---
# Si ya cuentas con una lista de columnas específicas, utilízala; de lo contrario, puedes usar todas las columnas:
# columnas_usuarios_activos = usuarios_activos.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_activos
    if pd.api.types.is_numeric_dtype(usuarios_activos[col])
]

print("Columnas numéricas a descomponer:", columnas_numericas)

# --- Descomposición de series temporales para cada columna numérica individual ---
for columna in columnas_numericas:
    # Crear una copia de la serie para trabajar
    serie_temporal = usuarios_activos[columna].copy()

    # Verificar si hay valores faltantes y tratarlos (interpolación y eliminación)
    if serie_temporal.isnull().any():
        serie_temporal = serie_temporal.interpolate()  # Rellenar NaN con interpolación
        serie_temporal = serie_temporal.dropna()        # Eliminar filas con valores faltantes

    # Verificar que no haya valores no finitos
    if not np.isfinite(serie_temporal).all():
        print(f'La columna {columna} contiene valores no finitos, se omite la descomposición.')
        continue

    # Intentar descomponer la serie temporal
    try:
        # Ajusta el parámetro "period" de acuerdo a la frecuencia de tus datos (por ejemplo, 12 para datos mensuales)
        descomposicion = seasonal_decompose(serie_temporal, model='additive', period=12)

        # Graficar la descomposición
        fig = descomposicion.plot()

        # Ajustar el tamaño de la figura con matplotlib
        plt.gcf().set_size_inches(10, 6)

        # Ajustar el título para evitar superposición
        fig.suptitle(f'Descomposición de la serie temporal de {columna}', fontsize=16, y=1.05)

        # Mostrar el gráfico
        plt.show()

    except ValueError as e:
        print(f"No se pudo descomponer la serie temporal de {columna}: {e}")

usuarios_activos = ""

usuarios_eliminados = pd.read_csv('drive/MyDrive/ColabNotebooks/Business_Payments/usuarios_eliminados_actualizado.csv')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Configurar el tamaño del gráfico
plt.figure(figsize=(12, 8))

# Crear un mapa de calor de los valores faltantes en usuarios_eliminados
sns.heatmap(usuarios_eliminados.isnull(), cbar=False, cmap="viridis", yticklabels=False)

# Agregar título
plt.title("Mapa de calor de valores faltantes en usuarios eliminados", fontsize=16)
plt.xlabel("Columnas", fontsize=12)
plt.ylabel("Filas", fontsize=12)

# Mostrar el gráfico
plt.show()

usuarios_eliminados.describe()

usuarios_eliminados.info()

# Obteniendo una lista de las columnas del DataFrame usuarios_eliminados
columnas_usuarios_eliminados = usuarios_eliminados.columns.tolist()

for i in columnas_usuarios_eliminados:
    print("===========================")
    print(f"Columna: {i}")
    print(usuarios_eliminados[i].value_counts().head(10))
    print()

import pandas as pd
import plotly.express as px

# --- Preparación del DataFrame ---
# Se asume que ya tienes cargado el DataFrame 'usuarios_eliminados'
# y que 'columnas_usuarios_eliminados' es una lista con los nombres de las columnas de interés.

# Opcional: Visualiza las primeras filas para confirmar la carga correcta
print(usuarios_eliminados.head())

# --- Filtrar columnas numéricas ---
# Si columnas_usuarios_eliminados contiene columnas no numéricas, filtramos solo las numéricas:
columnas_numericas = [
    col for col in usuarios_eliminados.columns
    if pd.api.types.is_numeric_dtype(usuarios_eliminados[col])
]

# Si prefieres obtener directamente todas las columnas numéricas del DataFrame:
# columnas_numericas = usuarios_eliminados.select_dtypes(include='number').columns.tolist()

print(f"Columnas numéricas a analizar: {columnas_numericas}")

# --- Generar y mostrar histogramas ---
for columna in columnas_numericas:
    fig = px.histogram(
        usuarios_eliminados,
        x=columna,
        title=f'Histograma de {columna} en usuarios eliminados',
        template='plotly_white'  # Estilo limpio de Plotly
    )
    # Ajustar la altura del gráfico
    fig.update_layout(height=500)
    # Mostrar el gráfico en Colab
    fig.show()

import pandas as pd
import plotly.express as px

# --- Cargar el DataFrame ---
# Se asume que ya tienes cargado tu DataFrame 'usuarios_eliminados'

# --- Definir la lista de columnas a analizar ---
# Obtener todas las columnas del dataset si no tienes una lista predefinida
columnas_usuarios_eliminados = usuarios_eliminados.columns.tolist()

# --- Identificar las columnas de interés ---
columnas_dataset = columnas_usuarios_eliminados

# --- Filtrar columnas numéricas ---
# Utilizamos describe() para extraer las columnas numéricas (describe solo calcula estadísticas para datos numéricos)
columnas_numericas = usuarios_eliminados[columnas_dataset].describe().columns.tolist()

print("Columnas numéricas detectadas:", columnas_numericas)

# --- Iterar sobre cada columna para identificar y graficar las categóricas con ≤ 10 valores únicos ---
for columna in columnas_dataset:
    # Procesamos únicamente las columnas que no son numéricas
    if columna not in columnas_numericas:
        # Contar la frecuencia de cada valor en la columna
        counts = usuarios_eliminados[columna].value_counts()

        # Si la cantidad de valores únicos es 10 o menos, graficamos
        if len(counts) <= 10:
            fig = px.pie(
                names=counts.index,
                values=counts.values,
                title=f'Distribución de {columna} en usuarios eliminados',
                template='plotly_white'  # Estilo visual limpio
            )
            # Ajustar la altura del gráfico
            fig.update_layout(height=300)
            # Mostrar el gráfico de pastel
            fig.show()

import pandas as pd
import plotly.express as px

# --- Asegúrate de tener cargado el DataFrame 'usuarios_eliminados' ---

# --- Define la lista de columnas a analizar ---
# Obtener todas las columnas si no tienes una lista predefinida
columnas_usuarios_eliminados = usuarios_eliminados.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_eliminados
    if pd.api.types.is_numeric_dtype(usuarios_eliminados[col])
]

print("Columnas numéricas a graficar:", columnas_numericas)

# --- Crear diagramas de caja para cada columna numérica ---
for columna in columnas_numericas:
    fig = px.box(
        usuarios_eliminados,
        y=columna,
        title=f'Boxplot de {columna} en usuarios eliminados',
        template='plotly_white'  # Estilo visual limpio
    )
    # Ajustar la altura del gráfico para una mejor visualización
    fig.update_layout(height=500)
    # Mostrar el gráfico
    fig.show()

import pandas as pd
import plotly.express as px

# --- Asegúrate de tener cargado el DataFrame 'usuarios_eliminados' ---

# --- Define la lista de columnas a analizar ---
# Obtener todas las columnas si no tienes una lista predefinida
columnas_usuarios_eliminados = usuarios_eliminados.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_eliminados
    if pd.api.types.is_numeric_dtype(usuarios_eliminados[col])
]

print("Columnas numéricas a graficar:", columnas_numericas)

# --- Crear diagramas de violín para cada columna numérica ---
for columna in columnas_numericas:
    fig = px.violin(
        usuarios_eliminados,
        y=columna,
        title=f'Violinplot de {columna} en usuarios eliminados',
        template='plotly_white'  # Estilo visual limpio
    )
    # Ajustar la altura del gráfico para una visualización óptima
    fig.update_layout(height=500)
    # Mostrar el gráfico
    fig.show()

import itertools
import plotly.express as px
import pandas as pd

# --- Asegúrate de tener cargado el DataFrame 'usuarios_eliminados' ---

# --- Define la lista de columnas a analizar ---
# Obtener todas las columnas si no tienes una lista predefinida
columnas_usuarios_eliminados = usuarios_eliminados.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_eliminados
    if pd.api.types.is_numeric_dtype(usuarios_eliminados[col])
]

print("Columnas numéricas a analizar:", columnas_numericas)

# --- Generar gráficos de dispersión con línea de tendencia para cada combinación de columnas numéricas ---
for c1, c2 in itertools.combinations(columnas_numericas, 2):
    fig = px.scatter(
        usuarios_eliminados,
        x=c1,
        y=c2,
        title=f'Gráfico de dispersión de {c1} vs {c2} en usuarios eliminados con línea de tendencia',
        trendline="ols",  # Agrega la línea de tendencia usando Ordinary Least Squares
        template='plotly_white'  # Estilo limpio y minimalista
    )
    # Ajustar los rangos y la altura del gráfico
    fig.update_layout(
        height=500,
        xaxis=dict(title=c1, automargin=True),
        yaxis=dict(title=c2, automargin=True)
    )
    # Mostrar el gráfico de dispersión con línea de tendencia
    fig.show()

import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
import pandas as pd

# --- Asegúrate de tener cargado el DataFrame 'usuarios_eliminados' ---

# --- Definir la lista de columnas a analizar ---
# Obtener todas las columnas si no tienes una lista predefinida
columnas_usuarios_eliminados = usuarios_eliminados.columns.tolist()

# --- Filtrar columnas numéricas de la lista de columnas de interés ---
columnas_numericas = [
    col for col in columnas_usuarios_eliminados
    if pd.api.types.is_numeric_dtype(usuarios_eliminados[col])
]

print("Columnas numéricas a descomponer:", columnas_numericas)

# --- Descomposición de series temporales para cada columna numérica individual ---
for columna in columnas_numericas:
    # Crear una copia de la serie para trabajar
    serie_temporal = usuarios_eliminados[columna].copy()

    # Verificar si hay valores faltantes y tratarlos (interpolación y eliminación)
    if serie_temporal.isnull().any():
        serie_temporal = serie_temporal.interpolate()  # Rellenar NaN con interpolación
        serie_temporal = serie_temporal.dropna()        # Eliminar filas con valores faltantes

    # Verificar que no haya valores no finitos
    if not np.isfinite(serie_temporal).all():
        print(f'La columna {columna} contiene valores no finitos, se omite la descomposición.')
        continue

    # Intentar descomponer la serie temporal
    try:
        # Ajusta el parámetro "period" de acuerdo a la frecuencia de tus datos (por ejemplo, 12 para datos mensuales)
        descomposicion = seasonal_decompose(serie_temporal, model='additive', period=12)

        # Graficar la descomposición
        fig = descomposicion.plot()

        # Ajustar el tamaño de la figura con matplotlib
        plt.gcf().set_size_inches(10, 6)

        # Ajustar el título para evitar superposición
        fig.suptitle(f'Descomposición de la serie temporal de {columna} en usuarios eliminados', fontsize=16, y=1.05)

        # Mostrar el gráfico
        plt.show()

    except ValueError as e:
        print(f"No se pudo descomponer la serie temporal de {columna}: {e}")